### ISSUE TITLE
Ability to download articles as zip files for importing into InDesign

### ISSUE THREAD

**Issue by StudioMercury** [StudioMercury/folio-author-plugin-for-wordpress#5]
Add the ability for articles (individuals or groups) to be downloaded as zips of the HTML and resources so they can be imported into InDesign.

**Comment by haemeulrich** [comment]
Are there any plans to integrate this?

**Comment by CreativeManner** [comment]
Yes please, Drupal already has this feature.

**Comment by StudioMercury** [comment]
Feature has been added.
