### ISSUE TITLE
What default templates should be seen in plugin?

### ISSUE THREAD

**Issue by JosephNardone** [StudioMercury/folio-author-plugin-for-wordpress#6]
Hi:
The Adobe documentation, download through Adobe, and download from git seem to contain different templates.  I am not seeing any templates install after moving the templates-dps folder into my Wordpress themes folder.  Are the templates working properly and what should I see if they are installed properly?
Thanks.

**Comment by StudioMercury** [comment]
The templates we've provided are very basic example templates, essentially a `Hello World!` to show that the template is working. Once you've moved the templates-dps into your theme folder you can start editing them any way you want. A template functions just the same as a template file for WordPress. You can have it output the `the_title()` or `the_content()` of the article and go from there. You can create new template by duplicating our examples and changing the template name at the top of the file. The template name at the top is the one you will see in the drop down list of templates when editing an article. The template example we gave was built off bootstrap. However, you can certainly provide any framework you want.

Right now, the plugin is still in a the pre-release stage. We were focused on locking down the core functionality of how the plugin works. Templates are so custom depending on the publication that we kept it very simple. Our next step is to work on providing a complete documentation about the hooks and filters we provide for templates so users can create more advanced interactivity with the templates. We'll be pushing an update soon with a cleaned up template folder.
