### ISSUE TITLE
Install plugin

### ISSUE THREAD

**Issue by olowek** [StudioMercury/folio-author-plugin-for-wordpress#7]
After installation new Wordpress site, you can not see Folio Author it on the menu. It is turned on and properly installed. Wordpress version 3.8.1, PHP 5.4 MySQL 5.0+
![zrzut ekranu 2014-02-23 o 11 17 22](https://f.cloud.github.com/assets/1681272/2240081/ceea27b6-9c73-11e3-8907-fba3bac2b740.png)

**Comment by olowek** [comment]
Facebook plugin work ...
![zrzut ekranu 2014-02-23 o 11 39 22](https://f.cloud.github.com/assets/1681272/2240129/eaca5eda-9c76-11e3-9ee1-807320466d96.png)

**Comment by StudioMercury** [comment]
Hi @olowek, 

Could you provide a little more information:
- Is this an installation of WP Multisite?
- Can you turn on PHP error reporting and let us know if anything comes up, you can add the following to your .htaccess file for your site:

`php_flag display_errors on`
`php_value error_reporting 6143`

**Comment by CoffeeAndCode** [comment]
@olowek you can try turning on WordPress error reporting as well: http://css-tricks.com/snippets/wordpress/turn-on-wordpress-error-reporting/

That should give you some more insight into what is breaking on your server.

**Comment by olowek** [comment]
Hi,

My installation WP is not Multisite. PHP version 5.3

**Comment by StudioMercury** [comment]
@olowek did you have any luck with enabling error reporting? Let us know if you get any errors after you've enabled error reporting in WordPress.

**Comment by olowek** [comment]
Yes, error is: Use of undefined constant **DIR** - assumed '**DIR**' in /home/wa200829/public_html/dps/wp-content/plugins/folio-author-plugin-for-wordpress/bootstrap.php on line 29

**Comment by olowek** [comment]
Sorry, PHP version  5.4

**Comment by StudioMercury** [comment]
@olowek I found the problem and have updated repo with the fix. If you download the new zip of the plugin at:

http://studiomercury.github.io/folio-author-plugin-for-wordpress/

It should resolve the problem.

**Comment by olowek** [comment]
I installed new version 1.2.2. There is no php error, but the plugin still does not work.

**Comment by StudioMercury** [comment]
If it's not throwing up any php errors and the plugin isn't showing up on the left menu, can you enable WP debugging: 

http://codex.wordpress.org/Debugging_in_WordPress

if you enable WP_DEBUG_LOG it will give you a log file inside wp-content. Can you see if any errors happen around the time of activating the plugin.

Additionally, what hosting environment are you using?

**Comment by olowek** [comment]
Debuging is on:

define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', true);
@ini_set('display_errors', 0);

At the moment, does not report errors.
Hosting is linux+cpanel

**Comment by StudioMercury** [comment]
Can you try setting the last line to this value:

@ini_set('display_errors', 1);
error_reporting(E_ALL);

setting it to 0 won't display any errors. this will show all errors for php.

**Comment by olowek** [comment]
Ok, no errors.

**Comment by StudioMercury** [comment]
I'd recommend trying another hosting space temporarily. The error you were receiving before: `Use of undefined constant __DIR__` should not have been happening.

`__DIR__` is a magic constant that was added in PHP 5.3.0. If your environment is 5.4.0 it should have had magic constants enabled. 

There could be something wrong with your installation of PHP and would be best to make sure the error isn't happening on another environment.

**Comment by olowek** [comment]
On other environment hosting works! Thanks.
